# -*- coding: utf-8 -*-
"""Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SgyhIJbIfWNw6lriMTGdAE1zvVYmR7fp
"""

!pip install -q sentence-transformers scikit-learn pandas numpy
!pip install -q faiss-cpu

from google.colab import files

uploaded = files.upload()
print("Uploaded:", list(uploaded.keys()))

import json
import re
import numpy as np
from sentence_transformers import SentenceTransformer
import faiss
from collections import defaultdict

# -------------------------------
# 1. Load and filter legal items
# -------------------------------
def is_legal_content(text: str) -> bool:
    if len(text) < 20:
        return False
    non_legal_patterns = [
        r"طبعه\s+\d{4}", r"مؤلف في سطور", r"المستشار أشرف مصطفى كمال",
        r"ليسانس الحقوق", r"نيابه القاهره", r"عضو هيئه المفوضين",
        r"صندوق الطوارئ", r"من ارشيف المؤلف", r"محتويات الكتاب",
        r"المذكره الايضاحيه", r"التعـــليق", r"احكام النقض",
    ]
    for pat in non_legal_patterns:
        if re.search(pat, text, re.IGNORECASE):
            return False
    legal_keywords = [
        "طلاق", "تطليق", "نفقة", "حضانة", "رؤية", "طاعة", "نشوز",
        "مهر", "صداق", "خلع", "عقوبة", "حبس", "غرامة", "إجراء",
        "حكم", "شرط", "استثناء", "نسب", "ميراث", "عدة", "ولاية"
    ]
    for kw in legal_keywords:
        if kw in text:
            return True
    return bool(re.search(r"[\u0600-\u06FF]{30,}", text))

def load_filtered_items(json_path: str):
    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    items = []
    for d in data:
        if not isinstance(d, dict) or "id" not in d or "content" not in d:
            continue
        try:
            _id = int(d["id"])
        except:
            continue
        txt = str(d["content"]).strip()
        if txt and is_legal_content(txt):
            items.append((_id, txt))
    return items

# 2. Compute embeddings
# -------------------------------
print("Loading filtered items...")
items = load_filtered_items("final_data.json")
print(f"Filtered items: {len(items)}")

print("\nLoading embedding model (mmbert-base-arabic-nli)...")
model = SentenceTransformer("Omartificial-Intelligence-Space/mmbert-base-arabic-nli")

texts = [text for _, text in items]
print("Computing embeddings (this may take a few minutes)...")
embeddings = model.encode(
    texts,
    normalize_embeddings=True,
    show_progress_bar=True,
    batch_size=32
)
print(f"Embeddings shape: {embeddings.shape}")

threshold = 0.90   # adjust: 0.90 - 0.98 (higher = stricter)
print(f"\nFinding near‑duplicate pairs (cosine > {threshold})...")

dim = embeddings.shape[1]
index = faiss.IndexFlatIP(dim)
index.add(embeddings.astype(np.float32))

adjacency = defaultdict(set)

# Search for each item against top‑k candidates (k=50 is enough, most items have few neighbours)
k = min(50, len(embeddings))
for i, emb in enumerate(embeddings):
    scores, idxs = index.search(emb.reshape(1, -1).astype(np.float32), k)
    for j, score in zip(idxs[0], scores[0]):
        if i != j and score > threshold:
            adjacency[i].add(j)
            adjacency[j].add(i)

num_pairs = sum(len(v) for v in adjacency.values()) // 2
print(f"Found {num_pairs} similar pairs (undirected).")

# 4. Build connected components (groups of near‑duplicates)
# -------------------------------
def get_connected_components(adj, n):
    visited = [False] * n
    components = []
    for i in range(n):
        if not visited[i]:
            comp = []
            stack = [i]
            visited[i] = True
            while stack:
                node = stack.pop()
                comp.append(node)
                for nb in adj[node]:
                    if not visited[nb]:
                        visited[nb] = True
                        stack.append(nb)
            components.append(comp)
    return components

components = get_connected_components(adjacency, len(items))
print(f"Number of connected components (including singletons): {len(components)}")

# Count components with size > 1
multi_components = [c for c in components if len(c) > 1]
print(f"Components with >1 item: {len(multi_components)}")

# 5. Merge each component into one chunk# -------------------------------
chunks = []
chunk_counter = 1

for comp in components:
    if len(comp) == 1:
        idx = comp[0]
        chunks.append({
            "id": f"chunk-{chunk_counter:04d}",
            "source_ids": [items[idx][0]],
            "content": items[idx][1],
            "num_items": 1
        })
    else:
        # Collect items in component, sort by original id (to keep logical order)
        comp_items = [(idx, items[idx][0], items[idx][1]) for idx in comp]
        comp_items.sort(key=lambda x: x[1])   # sort by source id
        merged_text = " ".join([txt for _, _, txt in comp_items])
        source_ids = [cid for _, cid, _ in comp_items]
        chunks.append({
            "id": f"chunk-{chunk_counter:04d}",
            "source_ids": source_ids,
            "content": merged_text,
            "num_items": len(comp)
        })
    chunk_counter += 1

# Sort chunks by the smallest source id for a natural order
chunks.sort(key=lambda x: min(x["source_ids"]))
print(f"\nTotal chunks after merging: {len(chunks)}")
output_path = "chunked_data.json"
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(chunks, f, ensure_ascii=False, indent=2)
print(f"\nSaved chunked data to {output_path}")

# 7. Preview merged examples (if any)
# -------------------------------
print("\nPreview of merged chunks (where num_items > 1):")
for ch in chunks:
    if ch["num_items"] > 2:
        print(f"\nID: {ch['id']}")
        print(f"Source IDs: {ch['source_ids']}")
        print(f"Content preview: {ch['content'][:1000]}...")
        break   # show only first merged chunk
else:
    print("No merges occurred (threshold may be too high). Try lowering threshold to 0.90.")

import json
with open("chunked_data.json", "r", encoding="utf-8") as f:
    chunks = json.load(f)

merged = [c for c in chunks if c["num_items"] > 1]
print(f"Total chunks: {len(chunks)}")
print(f"Chunks with merges: {len(merged)}")
print(f"Total original items represented: {sum(c['num_items'] for c in chunks)}")

files.download("chunked_data.json")

from google.colab import files

print("Please upload your law_dataset.csv file:")
uploaded_csv = files.upload()   # wait for CSV upload

print("\nPlease upload your existing chunked_data.json file:")
uploaded_json = files.upload()  # wait for JSON upload

# Get filenames (assuming single file each)
csv_filename = list(uploaded_csv.keys())[0]
json_filename = list(uploaded_json.keys())[0]

print(f"\nUploaded CSV: {csv_filename}")
print(f"Uploaded JSON: {json_filename}")

import pandas as pd
import json
import re

# Read CSV
df = pd.read_csv(csv_filename)
print(f"\nCSV shape: {df.shape}")
print(f"Columns: {df.columns.tolist()}")
print("\nFirst row sample:")
print(df.iloc[0].to_dict())
# Load existing chunks
with open(json_filename, "r", encoding="utf-8") as f:
    existing_chunks = json.load(f)
print(f"\nExisting chunks: {len(existing_chunks)}")

# Common Arabic filler words to remove from the start of answers
FILLER_PATTERNS = [
    r"^ايوه\s*[,،]?\s*",
    r"^أيوه\s*[,،]?\s*",        # إضافة الهمزة
    r"^اه\s*[,،]?\s*",
    r"^آه\s*[,،]?\s*",
    r"^أه\s*[,،]?\s*",
    r"^ايوا\s*[,،]?\s*",
    r"^أيوة\s*[,،]?\s*",
    r"^نعم\s*[,،]?\s*",
    r"^طبعاً\s*[,،]?\s*",
    r"^لا\s*[,،]?\s*",
    r"^لأ\s*[,،]?\s*",
]

def clean_answer(text: str) -> str:
    """Remove filler words and extra whitespace from answer."""
    if not isinstance(text, str):
        return ""
    text = text.strip()
    # Remove filler patterns from beginning
    for pat in FILLER_PATTERNS:
        text = re.sub(pat, "", text, count=1)
    # Remove any remaining leading punctuation like "،" or ","
    text = re.sub(r"^[,،]\s*", "", text)
    return text.strip()

# Apply cleaning to the 'answer' column
df["cleaned_answer"] = df["answer"].apply(clean_answer)

# Show example of cleaning
print("\nExample of cleaning:")
sample_answers = df[["answer", "cleaned_answer"]].head(3)
for idx, row in sample_answers.iterrows():
    print(f"\nOriginal: {row['answer'][:300]}...")
    print(f"Cleaned : {row['cleaned_answer'][:300]}...")

def transform_existing_chunk(chunk):
    old_id = chunk.get("id", "")
    # Extract number part after "chunk-"
    match = re.search(r"chunk-(\d+)", old_id)
    if match:
        new_id = match.group(1)
    else:
        new_id = old_id                # fallback (should not happen)
    return {
        "chunked_id": new_id,
        "content": chunk["content"],
        "num_items": chunk.get("num_items", 1),
    }

transformed_existing = [transform_existing_chunk(c) for c in existing_chunks]

if transformed_existing:
    max_existing_id = max(int(c["chunked_id"]) for c in transformed_existing)
else:
    max_existing_id = 0

next_id = max_existing_id + 1
new_chunks = []

for idx, row in df.iterrows():
    ans = row["cleaned_answer"]
    if not ans or len(ans) < 10:
        continue

    new_chunks.append({
        "chunked_id": str(next_id),   # e.g., "2471", "2472", ...
        "content": ans,
        "num_items": 1,
    })
    next_id += 1

print(f"\nCreated {len(new_chunks)} new chunks from CSV answers.")
print(f"New chunk IDs start from {max_existing_id + 1}")

# ============================================================
# Step 6: Merge and sort by numeric chunked_id
# ============================================================
combined = transformed_existing + new_chunks

def get_sort_key(chunk):
    return int(chunk["chunked_id"])

combined.sort(key=get_sort_key)

print(f"\nTotal chunks after merging and sorting: {len(combined)}")
print("First 5 chunked_ids:", [c["chunked_id"] for c in combined[:5]])
print("Last 5 chunked_ids:", [c["chunked_id"] for c in combined[-5:]])

output_filename = "final_chunked_data(1).json"
with open(output_filename, "w", encoding="utf-8") as f:
    json.dump(combined, f, ensure_ascii=False, indent=2)

print(f"\nSaved to {output_filename}")
files.download(output_filename)

import json
import inspect

def detect_category(text: str) -> str:
    """
    Detect legal category from Arabic text.
    Returns a string key.
    """
    if not isinstance(text, str):
        return "عام"

    t = text.lower()

    # Category keywords (order matters: more specific first)
    categories = {
        # Family law (divorce, marriage, custody, inheritance, maintenance, lineage)
        "طلاق": [
            "طلاق", "تطليق", "خلع", "فلس", "غياب", "هجر", "ضرر", "سجن", "فرقة", "الغياب",
            "التطليق", "النشوز", "إنذار الطاعة", "ناشز", "نشوز", "مكتب تسوية المنازعات",
            "الحَكَمين", "عرض الصلح", "الطلاق للضرر", "التطليق للضرر", "الطلاق للهجر",
            "الطلاق لاستحالة", "العيب", "مرض", "عجز", "عنن", "ختان", "الخلع", "المراجعة",
            "الرجعة", "الطلاق الرجعي", "الطلاق البائن", "الطلاق على مال", "الطلاق المعلق",
            "الطلاق المقترن بعدد", "الطلاق المتتابع", "الطلاق بالكناية", "التفويض بالطلاق",
            "إخفاء الطلاق", "إشهاد الطلاق", "توثيق الطلاق", "الطلاق الفار", "طلاق المريض",
            "طلاق السكران", "طلاق المكره", "طلاق الغضبان", "طلاق المجنون", "طلاق المعتوه",
            "قانون 25 لسنة 1920", "قانون 25 لسنة 1929", "قانون 1 لسنة 2000",
            "المادة 4", "المادة 5", "المادة 6", "المادة 9", "المادة 11", "المادة 12",
            "المادة 14", "المادة 18", "المادة 20", "التطليق لعدم الإنفاق", "التطليق للغيبة",
            "التطليق للحبس", "التطليق للعيب", "التطليق للزواج بأخرى", "التطليق للضرر (المادة 6)",
            "المادة 11 مكرر", "المادة 18 مكرر", "نفقة المتعة", "نفقة العدة", "العدة",
            "سن اليأس", "الإقراء", "ثلاثة أشهر", "قانون محاكم الأسرة", "قرار وزير العدل"
        ],
        "زواج": [
            "زواج", "نكاح", "عقد", "مهر", "صداق", "ولي", "كفاءة", "متعة", "رجعي", "بائن",
            "زوج", "زوجة", "خطوبة", "وثيقة زواج", "الزواج العرفي", "المأذون", "لائحة المأذونين",
            "المهر الصوري", "المهر الحقيقي", "مقدم الصداق", "مؤخر الصداق", "شرط الزواج",
            "منع التعدد", "المهر المسمى", "مهر المثل", "بدل المسمى", "عقد الزواج العرفي"
        ],
        "حضانة": [
            "حضانة", "رضاعة", "حاضن", "مسكن", "رؤية", "زيارة", "صغير", "طفل", "أطفال",
            "الحضانة", "الحاضنة", "الحاضن", "مسكن الحضانة", "سقوط الحضانة", "تسليم الصغير",
            "تنفيذ الرؤية", "الرؤية الأسبوعية", "أخصائي اجتماعي", "ضم الصغير", "الانتقال بالطفل"
        ],
        "ميراث": [
            "ميراث", "إرث", "تركة", "وصية", "توزيع", "نصيب", "فرض", "عصبة", "مواريث",
            "الميراث", "الورثة", "التركة", "الوصية", "الوقف", "هبة", "أصحاب الفروض",
            "العصبات", "الحجب", "العول", "الرد", "المناسخة", "ذوي الأرحام", "الفرائض",
            "سورة النساء", "القاتل لا يرث", "اختلاف الدين", "المفقود", "الجنين",
            "إشهاد الوراثة", "إعلام الوراثة", "تقسيم التركات", "الوصية الواجبة"
        ],
        "نفقة": [
            "نفقة", "مؤقتة", "متعضة", "عدة", "أجر", "رضاع", "ملبس", "مأكل", "النفقة",
            "نفقة المتعة", "نفقة العدة", "بدل الإجازات", "مكافأة نهاية الخدمة", "الإنفاق",
            "نفقة الأولاد", "نفقة الزوجة", "نفقة الصغار", "أجر الحضانة", "أجر الرضاع",
            "مسكن الحضانة", "الحبس في النفقة", "المادة 293 عقوبات", "المادة 76 مكرر",
            "أحكام النفقة مشمولة بالنفاذ المعجل", "قاضي تنفيذ الأحكام", "إكراه بدني",
            "امتناع عن النفقة", "اليسار", "تقدير النفقة", "نفقة زوجية", "نفقة عاجلة"
        ],
        "نسب": [
            "نسب", "ولد", "بنوة", "أبوة", "فراش", "لقيط", "إقرار", "ثبوت", "النسب",
            "الأبوة", "إثبات النسب", "البصمة الوراثية", "DNA", "إثبات الأبوة"
        ],

        # Labor
        "عمل": [
            "عمل", "عامل", "عمال", "موظف", "فصل", "تعسفي", "ساعات العمل", "أجر", "إجازات",
            "بيئة عمل", "صاحب العمل", "قطاع خاص", "عقد عمل", "أجر إضافي", "مكافأة نهاية الخدمة",
            "استقالة", "تمييز", "النقابة", "العمالة الأجنبية", "إنذار", "تحقيق", "خطأ جسيم",
            "مدة الإخطار", "مهلة الإخطار", "فصل تعسفي", "عبء الإثبات", "مكتب العمل",
            "المحكمة العمالية", "الوقف المؤقت", "حقوق العمال", "الإضراب", "الحد الأدنى للأجور"
        ],

        # Fraud
        "نصب": [
            "نصب", "احتيال", "تدليس", "الاستيلاء", "خداع", "المادة 336", "جريمة النصب",
            "شروع في النصب", "طرق احتيالية", "قصد جنائي", "الاستيلاء على مال", "النصاب",
            "بلغ النصب", "الاحتيال", "جمع تبرعات بدون ترخيص"
        ],

        # Intellectual property
        "براءات_اختراع": [
            "براءة اختراع", "براءات الاختراع", "اختراع", "ملكية فكرية", "الويبو", "TISC",
            "طلب البراءة", "المخترع", "الاختراع", "مكتب براءات الاختراع", "جدة", "خطوة ابتكارية",
            "تطبيق صناعي", "مطالبات", "الفحص الفني", "رسوم الصيانة", "حقوق المؤلف", "علامة تجارية",
            "نموذج صناعي", "مؤشر جغرافي", "حقوق التأليف والنشر", "الكوبي رايت", "الأسرار التجارية",
            "التصميمات الصناعية", "اتفاقية برن", "اتفاقية باريس", "الترخيص الإجباري"
        ],

        # Human rights & constitutional law
        "حقوق_الإنسان": [
            "حقوق الإنسان", "حرية", "تعبير", "تجمع", "إعلام", "صحافة", "حرية الصحافة",
            "حرية الإبداع", "حرية التعبير", "المظاهرات", "الأحزاب السياسية", "الشفافية",
            "سيادة القانون", "المساواة", "التمييز", "كرامة", "الحياة الخاصة", "المراسلات",
            "التنقل", "السفر", "القبض", "التلبس", "التعذيب", "الحبس الاحتياطي", "العدالة الانتقالية",
            "ضحايا", "تعويضات", "الحرية الشخصية", "الإعلان العالمي لحقوق الإنسان",
            "اتفاقية مناهضة التعذيب", "حقوق الطفل", "حقوق المرأة", "سيداو", "السجون",
            "الإشراف القضائي", "الرعاية الصحية للسجناء", "زيارة المحامي", "حقوق السجين",
            "جريمة ضد الإنسانية", "الحق في الصحة", "الحق في التعليم", "الحق في السكن",
            "الحق في المياة", "الحصول على المعلومات", "خط نجدة الطفل",
            "حماية البيانات الشخصية", "القانون رقم 151", "قاعدة لا ضرر ولا ضرار"
        ],

        # Judicial & criminal procedure, family court procedure, enforcement
        "قضاء": [
            "قضاء", "محكمة", "قاضي", "حكم", "دعوى", "نيابة", "الخصومة", "ترك الخصومة",
            "تنازع اختصاص", "حجية الأمر المقضي", "محكمة النقض", "محكمة الأسرة", "المحكمة الدستورية",
            "الطعن", "الاستئناف", "تنفيذ الأحكام", "التبليغ القانوني", "محضر", "النيابة العامة",
            "الرقابة الدستورية", "عدم دستورية", "المحكمة الدستورية العليا", "الدفع بعدم الدستورية",
            "القضاء العسكري", "محاكمة مدنيين", "الأمر المقضي", "درجات التقاضي", "التقاضي المدني",
            "حق التقاضي", "التحقيق الجنائي", "التحري", "الاستدلالات", "مسرح الجريمة",
            "الأدلة الجنائية", "البصمات", "تحليل DNA", "الطب الشرعي", "تشريح الجثة",
            "التحليل الباليستي", "تنميط الجاني", "أمر قبض", "حق المتهم في الصمت",
            "حق المتهم في محام", "إلغاء التوكيل", "المسؤولية المهنية للمحامي", "نقابة المحامين",
            "الدفاع عن المتهم", "تسوية المنازعات", "التحكيم", "الوساطة", "الصلح",
            "الشرط الجزائي", "فسخ العقد", "القوة القاهرة", "دعوى التعويض", "المسؤولية التقصيرية",
            "محكمة الجنايات", "محكمة الجنح", "الطعن بالنقض", "الحكم النهائي", "إعادة المحاكمة",
            "تحيز المحقق", "نيابة الأسرة", "النيابة العليا لشؤون الأسرة", "النيابات الكلية", "النيابات الجزئية",
            "قاضي تنفيذ أحكام الأسرة", "المكتب الفني", "قاعدة البيانات", "إدارة تنفيذ أحكام الأسرة",
            "أوامر على عريضة", "قاضي الأمور الوقتية", "إعلام الوراثة", "إشهاد الوفاة", "منع السفر",
            "نزاعات السفر للخارج", "الحجز على المرتب", "الاستشكال", "الاستدانة للنفقة",
            "أمر دفع", "الإكراه البدني", "الحبس في النفقة", "المادة 76 مكرر", "المادة 293 عقوبات",
            "مكتب تسوية المنازعات الأسرية", "محضر الصلح", "الصيغة التنفيذية", "ملف أسرة",
           "الطعن", "الاستشكال", "الأمر المقضي", "إنذار الطاعة", "نشوز", "ناشز", "النشوز", "اعتراض على إنذار الطاعة","الأخصائي الاجتماعي", "الأخصائي النفسي", "حضور الخبراء وجوبي"
        ],

        # International criminal law (ICC)
        "قانون_دولي_جنائي": [
            "المحكمة الجنائية الدولية", "الجنائية الدولية", "نظام روما الأساسي", "جرائم الحرب",
            "إبادة جماعية", "جرائم ضد الإنسانية", "جريمة العدوان", "أمر قبض", "مبدأ التكامل",
            "المدعي العام", "الدائرة التمهيدية", "الفحص الأولي", "التعاون مع المحكمة",
            "الضحايا", "التعويضات", "صندوق الضحايا", "عدم الإفلات من العقاب"
        ],

        # Medical error
        "خطأ_طبي": [
            "خطأ طبي", "إهمال طبي", "تشخيص خاطئ", "خطأ جراحي", "دواء خاطئ",
            "جرعة خاطئة", "تفاعل دوائي", "العدوى المكتسبة", "سوء التخدير", "إهمال ما بعد الجراحة",
            "الموافقة المستنيرة", "المسؤولية الطبية", "لجنة تحقيق نقابة الأطباء", "تقرير الخبرة الطبية"
        ],

        # Self-defense
        "دفاع_شرعي": [
            "دفاع شرعي", "الدفاع الشرعي", "حق الدفاع", "الخطر الحال", "الخطر الوشيك", "التناسب",
            "الضرورة", "التجاوز", "الذهول", "الخوف الشديد", "استفزاز", "الهجوم غير المشروع",
            "الاعتداء غير المشروع", "مقاومة سلطات", "الدفاع عن المال", "الدفاع عن النفس", "الدفاع عن الغير"
        ],

        # Bankruptcy
        "إفلاس": [
            "إفلاس", "إعسار", "تفليسة", "أمين التفليسة", "توقف عن الدفع", "إشهار الإفلاس",
            "إفلاس تقصيري", "إفلاس احتيالي", "إعادة الهيكلة", "تصفية أصول", "حقوق الدائنين"
        ],

        # Criminal law general
        "قانون_جنائي": [
            "جريمة", "عقوبة", "جنحة", "جناية", "محكمة الجنايات", "محكمة الجنح", "الاستدلالات",
            "التحري", "الضبط القضائي", "تحريك الدعوى الجنائية", "الدعوى المباشرة", "الشكوى",
            "البلاغ", "الأمر الجزائي", "النظام العام", "الردع", "العقوبات التكميلية"
        ],

        # Companies
        "شركات": [
            "شركة مساهمة", "شركة ذات مسئولية محدودة", "رأس المال", "أسهم", "مساهم",
            "مجلس إدارة", "جمعية عمومية", "تأسيس شركة", "تصفية", "اندماج", "الاستثمار",
            "المناطق الحرة", "عقد تأسيس", "نظام أساسي", "المصفي", "انقسام الشركات"
        ],

        # Consumer protection
        "حماية_المستهلك": [
            "حماية المستهلك", "مستهلك", "سلعة", "خدمة", "إعلان مضلل", "جهاز حماية المستلك",
            "استبدال", "استرجاع", "ضمان", "فاتورة", "غش تجاري", "احتكار"
        ],

        # Taxes
        "ضرائب": [
            "ضريبة", "ضرائب", "تهرب ضريبي", "الضرائب", "النظام الضريبي", "الإقرار الضريبي",
            "ضريبة الدخل", "ضريبة القيمة المضافة", "شريحة ضريبية", "حد الإعفاء", "مصلحة الضرائب",
            "الفحص الضريبي", "الاعتراض الضريبي", "غرامة تأخير"
        ],

        # Environment
        "بيئة": [
            "بيئة", "نهر", "بحر", "تلوث", "موارد طبيعية", "محمية", "البيئة", "تغير مناخي",
            "حماية البيئة", "الموارد الطبيعية", "المخلفات البلاستيكية", "الإبادة البيئية",
            "قانون البيئة", "جهاز شؤون البيئة", "التراخيص البيئية"
        ],

        # Default
        "عام": []
    }

    # Check each category
    for cat, keywords in categories.items():
        if cat == "عام":
            continue
        for kw in keywords:
            if kw in t:
                # Map to display names
                if cat in ["نفقة", "حضانة", "نسب", "زواج", "طلاق", "ميراث"]:
                    return cat
                if cat == "براءات_اختراع":
                    return "براءات اختراع"
                if cat == "حقوق_الإنسان":
                    return "حقوق الإنسان"
                if cat == "حماية_المستهلك":
                    return "حماية المستهلك"
                if cat == "قانون_دولي_جنائي":
                    return "قانون دولي"
                if cat == "خطأ_طبي":
                    return "خطأ طبي"
                if cat == "دفاع_شرعي":
                    return "دفاع شرعي"
                if cat == "إفلاس":
                    return "إفلاس"
                if cat == "قانون_جنائي":
                    return "قضاء"
                if cat in ["شركات", "عمل", "نصب", "قضاء", "ضرائب", "بيئة"]:
                    return cat


    return "عام"

# 1. Input file name (change if needed)
input_file = "final_chunked_data(1).json"

# 2. Read the JSON file
with open(input_file, "r", encoding="utf-8") as f:
    data = json.load(f)

# 3. Extract the list of chunks (if the file has a "chunks" key, use it; otherwise treat entire data as list)
if isinstance(data, list):
    chunks = data
elif isinstance(data, dict) and "chunks" in data:
    chunks = data["chunks"]
else:
    chunks = data

# 4. Add a "category" field to each chunk
for i, chunk in enumerate(chunks):
    content = chunk.get("content", "")
    category = detect_category(content)
    chunk["category"] = category
    if (i + 1) % 500 == 0:
        print(f"Processed {i+1} of {len(chunks)} chunks")

print(f"Successfully added category to {len(chunks)} chunks.")

# 5. Save the updated file (use a new name or overwrite)
output_file = "final_chunked_data_with_categories.json"
with open(output_file, "w", encoding="utf-8") as f:
    json.dump(chunks, f, ensure_ascii=False, indent=2)

print(f"Saved updated file to: {output_file}")

files.download("final_chunked_data_with_categories.json")